version: '3'

services:
  app:
    build: app/
    logging:
      options:
        max-size: "50M"
        max-file: "2"
    restart: always
    ports:
      - '8080:8080'
    volumes:
      - ./app/static:/usr/src/app/static
      - ./app/media:/usr/src/app/media
    env_file:
      - .env
    depends_on:
      - db


  db:
    image: mysql:5.7
    environment:
      MYSQL_DATABASE: 'db_django'
      MYSQL_USER: 'django_user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    restart: always
    volumes:
      - ./db_django:/var/lib/mysql