# Generated by Django 3.2.9 on 2021-11-04 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='image',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
