# Generated by Django 3.2.9 on 2021-11-04 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0002_auto_20211104_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='file',
            field=models.ImageField(upload_to='%Y/%m/%d/', verbose_name='Изображение'),
        ),
    ]
