# Generated by Django 3.2.9 on 2021-11-04 10:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0003_alter_image_file'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='image',
            name='height',
        ),
        migrations.RemoveField(
            model_name='image',
            name='width',
        ),
    ]
