# Generated by Django 3.2.9 on 2021-11-04 20:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('img_uploader', '0009_alter_image_p_hash'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='width',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
